name: C/C++ CI

on:
  push:
    branches: [ "NetHack-3.7" ]
  pull_request:
    branches: [ "NetHack-3.7" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: nhsetup
      run: sys/unix/setup.sh sys/unix/hints/linux.370
    - name: fetch-lua
      run: make fetch-lua
    - name: make
      run: make
    - name: fetch-texlive
      run: apt install texlive
    - name: Guidebook
      run: make Guidebook ; make Guidebook.txt ; make Guidebook.pdf


