name: C/C++ CI

on:
  push:
    branches: [ "NetHack-3.7" ]
  pull_request:
    branches: [ "NetHack-3.7" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fetch-texlive
      run: sudo apt install texlive
    - name: nhsetup
      run: sys/unix/setup.sh sys/unix/hints/linux.370
    - name: fetch-lua
      run: make fetch-lua
    - name: make NetHack
      run: |
            make
            make Guidebook
            make Guidebook.txt
            make Guidebook.pdf
    - name: Archive Guidebook
      uses: actions/upload-artifact@v4
      with:
          name: Guidebook.pdf
          path: doc/Guidebook.pdf

            


